<!DOCTYPE html>
<html>
  <head>
  <!--HEADS UP! I'm currently a beginner so this code is constantly being adjusted -->
  <title> giGABYte Creatives</title>
   <!--add icon link -->
  </head>

  <body>
      <!-- Home Start-->
      
  
      
</html>
